---
title: "DMM presentation"
author: "Marine Ballutaud"
date: "10/12/2021"
output: html_document
---
dmm: definition, reference and objective
+ code functioning among directories 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#setup
```{r}
#install.packages("deSolve")
library(deSolve) #solver for Ordinary Differential Equations (ODE)
```

#load data and functions
```{r}
load("data/random-sources-100simu.Rdata") # matrix of Brownian trajectories - see script product-brownian-sources.R to produce them

source("data/parameters.R") #load all parameters for in-silico experiment, case study and layout of graphics


source("R/dmm-functions.R") #load all procedures for estimating isotopic values and food source proportions
```



#create figure 2
```{r}
#source("R/figure2.R")
```

#create figure 3
```{r}
#source("R/figure3.R")
```

#create figure 4
```{r}
#source("R/figure4.R")
```

#create figure 5
```{r}
#source("R/figure5.R")
#dev.off()
```

#create figure 6
```{r}
#source("R/figure6.R")
#file.show("R/figure6.R")
#source.with.encoding("R/figure6.R", encoding = "utf8")

```


#results
All results and figures are available in directory named dmm/output.

